### ISSUE TITLE
Thank you so much! <3 I hope we get more options for ScriptableObject cases too!

### ISSUE THREAD

**Issue by hoangcuongzk1** [snoopyuj/DeleteMissingScripts#1]
Thank you so much! <3 I hope we get more options for ScriptableObject cases too!

**Comment by hoangcuongzk1** [comment]
<img width="353" alt="image" src="https://github.com/user-attachments/assets/ae939655-3cfe-4ed3-8c72-74535cbba410">

**Comment by bwaynesu** [comment]
<img height="280" alt="Preview02" src="https://github.com/snoopyuj/DeleteMissingScripts/raw/main/Preview/Preview02.png"/>

Here you go. I apologize that the interface is still quite basic, but the functionality should work without issues.

Unfortunately, ScriptableObjects with missing scripts can't be selected in the list at the moment; only their file names can be displayed. I'll work on improving this in the future if possible.
